### PR TITLE
Updated update_test_result

### PR DESCRIPTION
**Pull request by jay-2597**
Updated -- update_test_result 

put instead of post result so that new execution id is not created every time updating test result.

### CODE REVIEW

**Comment by jay-2597** [comment]
@nassauwinter @crapitea Please review request -- Updated -- update_test_result

put instead of post result so that new execution id is not created every time updating test result.

**Comment by nassauwinter** [comment]
Hi @jay-2597! Thank you for your contribution.

The official method from Zephyr Scale Server API is POST. PUT is not supported/documented. So I suggest to leave update_test_result method as is.

Anyway, could you please add a new method for that endpoint? Name it like modify_test_result with explicit statement in its docstring that the method is not supported/documented in official documentation; it works and makes it possible to modify a test result.

**Comment by jay-2597** [comment]
@nassauwinter @crapitea ,

put is documented in documentation of zephyr scale server api can you follow the link as below endpoint:
https://support.smartbear.com/zephyr-scale-server/api-docs/v1/
/testrun/{testRunKey}/testcase/{testCaseKey}/testresult

**Comment by nassauwinter** [comment]
@jay-2597,

My mistake. Here is a bug in update_test_result. Look at the create_test_result and update_test_result: both use post while update_test_result expected to use put. Would you modify your PR to fix that?

**Review by nassauwinter — APPROVED** [review]

**Pull request merged**
